### ISSUE TITLE
C# Driver

### ISSUE THREAD

**Issue by classifieds-dev** [aws/aws-sigv4-auth-cassandra-java-driver-plugin#10]
I don't know if this is the right place to ask. However, I have been trying to put together the code to connect to managed Cassandra instance with little luck. Will something like this driver but for c# be required to connect to mcs using roles and federated entities? I think I can use username and password but it doesn't look like that is the correct way to do it. However, I don't think a c# driver for SigV4AuthProvider exists yet. Right?

**Comment by dchenbec** [comment]
You can use username/password for authentication by using service-specific credentials associated with an IAM user. You can learn more at https://docs.aws.amazon.com/keyspaces/latest/devguide/programmatic.credentials.html.

This SigV4 plugin enables you to manage access to your resources in Amazon Keyspaces by using IAM entities such as IAM users and roles, and federated identities. This provides you greater convenience if you're accessing Amazon Keyspaces from EC2 by using EC2 Instance Roles and avoiding manual configuration of credentials. Although there is not a SigV4 plugin for C# currently, if you're still having problems accessing Amazon Keyspaces using the C# driver with username/password authentication please start a thread in the forums (https://forums.aws.amazon.com/forum.jspa?forumID=357) and provide more details on the errors you're seeing.

I will also share your interest in a plugin for C# with our team as input for our roadmap.

**Comment by classifieds-dev** [comment]
Hello, dchenbec

I was able to use the c# data stax driver working. I was missing configuration settings for the load balancing strategy. A step easily missed since no AWS documentation exists for c#. So I was using mostly what I had found on the internet not related to AWS which did not include info about setting up a load balancing strategy.

One recommendations would be to add docs for connecting using c#. I was successfully able to  connect using the following configuration.

```csharp
            var pathToCAFile = $"{Directory.GetCurrentDirectory()}/AmazonRootCA1.pem";
            X509Certificate2[] certs = new X509Certificate2[] { new X509Certificate2(pathToCAFile, "amazon") };
            lambdaContext.Logger.LogLine($"CERT DATA: {certs[0]}");
            X509Certificate2Collection certificateCollection = new X509Certificate2Collection(certs);
            var options = new Cassandra.SSLOptions(SslProtocols.Tls11, true, ValidateServerCertificate);
            options.SetCertificateCollection(certificateCollection);
            options.SetHostNameResolver((ipAddress) => "cassandra.us-east-1.amazonaws.com");
            Cluster cluster = Cluster
                                .Builder()
                                 .WithCredentials("<username>", "<password>")
                                .WithPort(9142)
                                .AddContactPoint("cassandra.us-east-1.amazonaws.com")
                                .WithSSL(options)
                                .WithLoadBalancingPolicy(new TokenAwarePolicy(new DCAwareRoundRobinPolicy("us-east-1")))
                                 .WithExecutionProfiles(p => p
                                    .WithProfile("insert", opts => opts
                                        .WithConsistencyLevel(ConsistencyLevel.LocalQuorum)
                                    )
                                    .WithProfile("delete", opts => opts
                                        .WithConsistencyLevel(ConsistencyLevel.LocalQuorum)
                                    )
                                 )
                                .Build();
```

**Comment by dchenbec** [comment]
Thanks for the information, @classifieds-dev! I'll pass this info along to the team.

**Comment by njlr** [comment]
For me this bit was the only missing piece:

```
options.SetHostNameResolver((ipAddress) => "cassandra.us-east-1.amazonaws.com");
```

**Comment by dsharkou** [comment]
1. We should use protocol version `SslProtocols.Tls12` (as for now)
2. It's not correct in [dotnet core documetation](https://docs.aws.amazon.com/keyspaces/latest/devguide/using_dotnetcore_driver.html) - we should use `AmazonRootCA1.pem` certificate (fortunately it was mentioned above as well), which you can download from https://www.amazontrust.com/repository/ 

So now it does work for me
