### ISSUE TITLE
Generating invalid signatures on Windows platforms

### ISSUE THREAD

**Issue by shirayukikitsune** [aws/aws-sigv4-auth-cassandra-java-driver-plugin#12]
The method `generateSignature` generates an invalid `stringToSign` on Windows platforms.

It uses the `String.format`, using `%n` as line separators which corresponds to the OS line separator. In Windows, that is `\r\n`, but [according to the specs](https://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html), the line separator must be `\n`.

The same also applies in the method `canonicalizeRequest`.

**Comment by dchenbec** [comment]
Thanks for the report, we'll take a look.

**Comment by dchenbec** [comment]
@shirayukikitsune the fix is released as version 4.0.3. Please let us know if you see any further issues!

**Comment by shirayukikitsune** [comment]
I confirmed that the problem is now fixed, thank you!
