### ISSUE TITLE
Injecting CqlSession with custom Cassandra config doesn't work

### ISSUE THREAD

**Issue by jereztech** [aws/aws-sigv4-auth-cassandra-java-driver-plugin#23]
Hello, 
I'm trying to connect to AWS Keyspaces. Without CustomCassandraConfiguration it works, but with CustomCassandraConfiguration it doesn't work. I need a CustomCassandraConfiguration to add some custom converters https://docs.spring.io/spring-data/cassandra/docs/current/reference/html/#customconversions.java

**Comment by dchenbec** [comment]
Let me see if I can reproduce locally. Could you provide some details on the error(s) you're seeing?

**Comment by jereztech** [comment]
`AllNodesFailedException: Could not reach any contact point, make sure you've provided valid addresses (showing first 1 nodes, use getAllErrors() for more): Node(endPoint=cassandra.us-east-1.amazonaws.com:9142): [com.datastax.oss.driver.api.core.DriverTimeoutException: [s0|control|id: 0xf08a9, L:/XXX.XXX.XXX - R:cassandra.us-east-1.amazonaws.com/XXX.XXX.XXX:9142] Protocol initialization request, step 1 (OPTIONS): timed out after 5000 ms]`
