### ISSUE TITLE
 DefaultTopologyMonitor and DefaultTokenFactoryRegistry Warning

### ISSUE THREAD

**Issue by mehmetdreamgames** [aws/aws-sigv4-auth-cassandra-java-driver-plugin#24]
We have moved our cassandra cluster to Amazon Keyspaces, in practice we did not face critical issues so far. But there's an already open discussion for `DefaultTopologyMonitor` and `TokenFactory` warnings.  We have facing issues related to these warnings when we attempted to use in production.  

- `Control node .../...:9142 has an entry for itself `
- `Unsupported partitioner 'com.amazonaws.cassandra.DefaultPartitioner', token map will be empty.`

We have following configuration as it's suggested by AWS experts in the [discussion](https://forums.aws.amazon.com/thread.jspa?messageID=945795): 

`    
metadata {
                schema {
                    enabled = false
                }
                token-map {
                    enabled = false
                }
            }
 `
 
 The warnings are appearing after a period like ~24 hours without any action on our side. You can see the below chart, we have ~35k warnings coming from 10 different pods .
 
![image](https://user-images.githubusercontent.com/96425748/150737356-a5fc7f76-ab7c-48f9-af90-1c04cd5137a1.png)

We are using AWS sigv4 plugin and we implemented as it's suggested in [Sample Application](https://github.com/aws-samples/amazon-keyspaces-examples/tree/f107bd79d67341a97d052957270b7aecf833c10b/java/datastax-v4/connection-vpc-endpoint)

**Comment by BarisGece** [comment]
https://stackoverflow.com/questions/70877020/amazon-keyspaces-defaulttokenfactoryregistry-and-defaulttopologymonitor-causes

**Comment by dchenbec** [comment]
Keyspaces now supports the standard `RandomPartitioner` and can be changed at the account level via either the console or via CQL: https://docs.aws.amazon.com/keyspaces/latest/devguide/working-with-partitioners.html
